### PR TITLE
feat/fastify@v4

### PR DESCRIPTION
**Pull request by simonecorsi**
ref #152

### CODE REVIEW

**Comment by simonecorsi** [comment]
@dnlup Something changed in the errorHandler, `reply.statusCode` is always returning 200

**Comment by simonecorsi** [comment]
Following note on [setErrorHandler](https://www.fastify.io/docs/latest/Reference/Server/#seterrorhandler):

`Note: If the error statusCode is less than 400, Fastify will automatically set it at 500 before calling the error handler.`

I've manually added this and tests now work, but I think the problem has to do with the fact that now errorHandler are encapsulated

**Review by dnlup — APPROVED** [review]
I think this approach is the best we can do for now, I added a few line of documentation 😉

**Comment by simonecorsi** [comment]
lgtm! Thanks for the documentation 🚀

**Pull request merged**
