### PR TITLE
Improve SDK integration

### LINKED ISSUE #3: Consider using Sentry default options for skipping status codes
I didn't want to use Sentry hooks to skip the event reporting for some status codes. I think we should benchmark the difference and consider using the default Sentry hooks if the drop isn't big. I think it's better to have a single point to handle the skipping, it's less confusing.

### LINKED ISSUE #5: Improve the allowedStatusCode option override
Avoid having a big array with all the status code and see if we can do some filtering based on strings, eg: `5xx`

### LINKED ISSUE #112: Don't use `extra` field
This filed has been deprecated, we should use `setContext` instead of `setExtra`.

### LINKED ISSUE #114: Improve integration with sdk
Looking at how Sentry is integrated in Express (https://github.com/getsentry/sentry-javascript/blob/master/packages/node/src/handlers.ts) I think we can pick up a thing or two and apply them here, for example:

* use a function (`shouldHandlerError` in the Express integration) to customize the event filtering instead of our array of statusCodes
* improve how we enrich the event data

Implementing these changes would also resolve issues #5 and #3

### LINKED ISSUE #115: Support Sentry Performance API
In its latest versions Sentry has added tracing performance capabilities, it would be nice to be able to support that, using an option to enable/disable the functionality or maybe using a separate plugin 🤔

### PR DESCRIPTION
**Pull request by dnlup**
Closes #3 
Closes #5 
Closes #112 
Closes #114 
Closes #115 

Steps:

- [x] implementation
- [x] double export to export util functions
- [x] tests
- [x] types
- [x] docs
- [x] benchmarks

In this PR we are:

* removing the filtering with `allowedStatusCodes` in favour of using a function
* adding more functions to configure the extracting of metadata to attach to the sentry event
* removing the `onErrorFactory` in favour of register your own error handler manually
* adding a hook to customise the error response in the default error handler
* exporting a `/utils` path to expose out internal functions to handle event metadata

### CODE REVIEW

**Comment by dnlup** [comment]
I think I will start to introduce support of the Sentry Performance API in this PR. The code is so intertwined with the work done so far that it makes sense to give it a go now.

**Comment by simonecorsi** [comment]
Can we schedule a pair review tomorrow since it's a bit old and it'll be easier :)

**Comment by dnlup** [comment]
> Can we schedule a pair review tomorrow since it's a bit old and it'll be easier :)

**Pull request merged**
