### PR TITLE
ci(actions): remove action to cache node_modules and remove redundant action

### PR DESCRIPTION
**Pull request by dnlup**
This is an attempt to fix errors of EEPERM during npm i
on windows.

### CODE REVIEW

**Comment by dnlup** [comment]
@simonecorsi So it seems the the node actions downloaded a version of npm with [this issue](https://github.com/npm/cli/issues/4341). Pinning the npm version resolves the problem. I think we should consider pinning the action version instead, if it works we would be able to catch these problems in a PR opened by Dependabot which upgrades the action itself. Let me try this before deciding on the action to take.

**Comment by dnlup** [comment]
Scratch that, the version is setup in the maztrix, so we are always downloading the latest and the greatest.

**Comment by dnlup** [comment]
One other thing, the node action should already have the cache (https://github.com/actions/setup-node#caching-packages-dependencies) so using another action for that might be redundant.

**Comment by simonecorsi** [comment]
> One other thing, the node action should already have the cache (https://github.com/actions/setup-node#caching-packages-dependencies) so using another action for that might be redundant.

Nice catch! I'll remove it from other jobs too!

**Review by simonecorsi — APPROVED** [review]

**Comment by dnlup** [comment]
It should be ready to land now. PTAL.

**Pull request merged**
